# src/parsers/parser_config.yaml

section_headers:
  - Requesting Party
  - Insured Information
  - Adjuster Information
  - Assignment Information
  - Assignment Type
  - Additional details/Special Instructions
  - Attachment(s)

patterns:
  Requesting Party:
    Insurance Company: '(?i)Insurance\s*(?:Company|Carrier)?\s*:?\s*(.*?)\s*(?=\n|$)'
    Handler: '(?i)(?:Handler|Adjuster)\s*:?\s*(.*?)\s*(?=\n|$)'
    Carrier Claim Number: '(?i)(?:Carrier\s*)?(?:Claim|File)\s*(?:Number|#)\s*:?\s*(\S+)'
  
  Insured Information:
    Name: '(?i)(?:Insured\s*)?Name\s*:?\s*(.*?)\s*(?=\n|$)'
    Contact #: '(?i)(?:Contact|Phone)\s*(?:#|Number)\s*:?\s*(\+?1?[\s.-]?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})'
    Loss Address: '(?i)(?:Loss|Damaged?)\s*Address\s*:?\s*(.*?)\s*(?=\n|$)'
    Public Adjuster: '(?i)Public\s*Adjuster\s*:?\s*(.*?)\s*(?=\n|$)'
    Owner or Tenant: '(?i)(?:Is\s*the\s*insured\s*an?\s*)?Owner\s*or\s*(?:a\s*)?Tenant\s*(?:of\s*the\s*loss\s*location)?\s*:?\s*(Owner|Tenant|Yes|No)'

  Adjuster Information:
    Adjuster Name: '(?i)Adjuster\s*Name\s*:?\s*(.*?)\s*(?=\n|$)'
    Adjuster Phone Number: '(?i)(?:Tel|Telephone|Cell|Mobile)\s*(?:Number|#)\s*:?\s*(\+?1?[\s.-]?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})'
    Adjuster Email: '(?i)(?:Adjuster\s*)?Email\s*:?\s*([\w\.-]+@[\w\.-]+\.\w+)'
    Job Title: '(?i)(?:Job|Position)\s*Title\s*:?\s*(.*?)\s*(?=\n|$)'
    Address: '(?i)(?:Company|Office)?\s*Address\s*:?\s*(.*?)\s*(?=\n|$)'
    Policy #: '(?i)Policy\s*(?:#|Number)\s*:?\s*(\w+)'

  Assignment Information:
    Date of Loss/Occurrence: '(?i)Date\s*of\s*(?:Loss|Occurrence|Damage)\s*:?\s*(\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|\w+\s+\d{1,2},?\s*\d{4})'
    Cause of loss: '(?i)Cause\s*of\s*(?:loss|damage)\s*:?\s*(.*?)\s*(?=\n|$)'
    Facts of Loss: '(?i)Facts\s*of\s*Loss\s*:?\s*(.*?)\s*(?=\n|$)'
    Loss Description: '(?i)(?:Loss|Damage)\s*Description\s*:?\s*(.*?)\s*(?=\n|$)'
    Residence Occupied During Loss: '(?i)Residence\s*Occupied\s*During\s*Loss\s*:?\s*(Yes|No|Unknown)'
    Was Someone home at time of damage: '(?i)(?:Was\s*Someone|Anyone)\s*home\s*(?:at|during)\s*(?:time|moment)\s*of\s*damage\s*:?\s*(Yes|No|Unknown)'
    Repair or Mitigation Progress: '(?i)Repair\s*(?:or|/)\s*Mitigation\s*Progress\s*:?\s*(.*?)\s*(?=\n|$)'
    Type: '(?i)Type\s*(?:of\s*(?:Loss|Damage|Claim))?\s*:?\s*(.*?)\s*(?=\n|$)'
    Inspection type: '(?i)Inspection\s*type\s*:?\s*(.*?)\s*(?=\n|$)'

  Assignment Type:
    Wind: '(?i)Wind\s*(?:\[\s*([xX])\s*\]|\(\s*([xX])\s*\)|:?\s*(Yes|No))'
    Structural: '(?i)Structural\s*(?:\[\s*([xX])\s*\]|\(\s*([xX])\s*\)|:?\s*(Yes|No))'
    Hail: '(?i)Hail\s*(?:\[\s*([xX])\s*\]|\(\s*([xX])\s*\)|:?\s*(Yes|No))'
    Foundation: '(?i)Foundation\s*(?:\[\s*([xX])\s*\]|\(\s*([xX])\s*\)|:?\s*(Yes|No))'
    Other: '(?i)Other\s*(?:\[\s*([xX])\s*\]|\(\s*([xX])\s*\)|:?\s*(Yes|No))(?:\s*-?\s*provide\s*details?\s*:?\s*(.*?))?\s*(?=\n|$)'

  Additional details/Special Instructions:
    Additional details/Special Instructions: '(?i)(?:Additional\s*details?|Special\s*Instructions?)\s*:?\s*(.*)'

  Attachment(s):
    Attachment(s): '(?i)Attachments?\s*(?:\(s\))?\s*:?\s*(.*)'

additional_patterns:
  Requesting Party:
    Insurance Company: '(?i)(?:Insurance|Carrier)\s*:?\s*(.*?)\s*(?=\n|$)'
    Handler: '(?i)(?:Claim|File)\s*(?:Handler|Manager)\s*:?\s*(.*?)\s*(?=\n|$)'
    Carrier Claim Number: '(?i)(?:File|Reference)\s*(?:Number|#)\s*:?\s*(\S+)'

  Insured Information:
    Name: '(?i)(?:Claimant|Policyholder)\s*:?\s*(.*?)\s*(?=\n|$)'
    Contact #: '(?i)(?:Tel|Telephone|Cell|Mobile)\s*:?\s*(\+?1?[\s.-]?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})'
    Loss Address: '(?i)(?:Property|Incident)\s*Address\s*:?\s*(.*?)\s*(?=\n|$)'
    Public Adjuster: '(?i)(?:PA|Pub\.\s*Adj\.)\s*:?\s*(.*?)\s*(?=\n|$)'

  Adjuster Information:
    Adjuster Name: '(?i)(?:Assigned|Handling)\s*Adjuster\s*:?\s*(.*?)\s*(?=\n|$)'
    Adjuster Phone Number: '(?i)(?:Tel|Telephone|Cell|Mobile)\s*(?:Number|#)\s*:?\s*(\+?1?[\s.-]?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})'
    Adjuster Email: '(?i)(?:E-?mail|Contact)\s*:?\s*([\w\.-]+@[\w\.-]+\.\w+)'

  Assignment Information:
    Date of Loss/Occurrence: '(?i)(?:DOL|Loss\s*Date)\s*:?\s*(\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|\w+\s+\d{1,2},?\s*\d{4})'
    Cause of loss: '(?i)(?:Loss\s*Type|Peril)\s*:?\s*(.*?)\s*(?=\n|$)'
    Type: '(?i)(?:Claim|Loss)\s*Type\s*:?\s*(.*?)\s*(?=\n|$)'
    Inspection type: '(?i)(?:Inspection|Assessment)\s*(?:Type|Method)\s*:?\s*(.*?)\s*(?=\n|$)'

  Additional details/Special Instructions:
    Additional details/Special Instructions: '(?i)(?:Notes|Comments|Remarks)\s*:?\s*(.*)'

date_formats:
  - '%m/%d/%Y'
  - '%d/%m/%Y'
  - '%Y-%m-%d'
  - '%B %d, %Y'
  - '%b %d, %Y'
  - '%d %B %Y'
  - '%d %b %Y'
  - '%Y/%m/%d'
  - '%d-%m-%Y'
  - '%Y.%m.%d'
  - '%d.%m.%Y'
  - '%m-%d-%Y'
  - '%Y%m%d'
  - '%B %-d, %Y'
  - '%b %-d, %Y'
  - '%Y-%m-%dT%H:%M:%S'
  - '%Y-%m-%dT%H:%M:%S.%fZ'

boolean_values:
  positive:
    - 'yes'
    - 'y'
    - 'true'
    - 't'
    - '1'
    - 'x'
    - '[x]'
    - '[X]'
    - '(x)'
    - '(X)'
  negative:
    - 'no'
    - 'n'
    - 'false'
    - 'f'
    - '0'
    - '[ ]'
    - '()'
    - '[N/A]'
    - '(N/A)'

valid_extensions:
  - '.pdf'
  - '.docx'
  - '.xlsx'
  - '.zip'
  - '.png'
  - '.jpg'
  - '.jpeg'
  - '.gif'
  - '.txt'
  - '.csv'

url_validation:
  use_external_library: true